import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { FONT_PACK_CATALOGUE } from "../src/font-pack-catalogue";

/**
 * `src/font-pack-catalogue.ts` is generated by
 * `tools/build_font_packs.py --write-catalogue` from the pack ZIPs a
 * release publishes.  This regenerates it from the same packs an already
 * built copy of, kept outside the repository, and checks the committed
 * module still matches byte for byte - so a hand edit or a stale build does
 * not go unnoticed.  It skips itself where that copy is not present, such as
 * a machine that has never built the packs.
 */
const FONT_PACKS_DIR = process.env.MIRO_CANVAS_FONT_PACKS_DIR;

describe("the generated font pack catalogue", () => {
  it.runIf(FONT_PACKS_DIR !== undefined && existsSync(FONT_PACKS_DIR))(
    "matches tools/build_font_packs.py --write-catalogue run against the built packs",
    () => {
      const scratch = mkdtempSync(join(tmpdir(), "font-pack-catalogue-"));
      const outPath = join(scratch, "font-pack-catalogue.ts");
      // Regenerate straight from the already-built packs: no network, no
      // rebuild, the same catalogue-writing code path the tool ships.
      execFileSync("python", [
        "-c",
        [
          "import json, sys, zipfile",
          "sys.path.insert(0, 'tools')",
          "import build_font_packs as bfp",
          `catalogue = json.loads(open(r'${FONT_PACKS_DIR}/catalogue.json', encoding='utf-8').read())`,
          "entries = []",
          "for item in catalogue:",
          `    with zipfile.ZipFile(r'${FONT_PACKS_DIR}/' + item['file']) as bundle:`,
          "        manifest = json.loads(bundle.read('pack.json'))",
          "    entries.append({**item, 'title': manifest['title'], 'description': manifest['description']})",
          `bfp.write_catalogue_module(entries, r'${outPath}')`,
        ].join("\n"),
      ], { cwd: process.cwd() });
      const regenerated = readFileSync(outPath, "utf-8");
      const committed = readFileSync(join(process.cwd(), "src/font-pack-catalogue.ts"), "utf-8");
      rmSync(scratch, { recursive: true, force: true });
      expect(committed).toBe(regenerated);
    },
  );

  it("carries every pack the plugin knows how to download, each with a size and a checksum", () => {
    for (const entry of FONT_PACK_CATALOGUE) {
      expect(entry.id).toMatch(/^[a-z][a-z0-9-]*$/u);
      expect(entry.file).toBe(`fonts-${entry.id}.zip`);
      expect(entry.bytes).toBeGreaterThan(0);
      expect(entry.sha256).toMatch(/^[0-9a-f]{64}$/u);
      expect(entry.title.en).not.toBe("");
      expect(entry.title.ru).not.toBe("");
      expect(entry.description.en).not.toBe("");
      expect(entry.description.ru).not.toBe("");
    }
    expect(FONT_PACK_CATALOGUE.map((entry) => entry.id)).toEqual(["miro", "miro-cjk", "word", "excalidraw"]);
  });
});
