"""Bundle actual PDF/PPTX outputs of the real Obsidian export-pages scenario.

Source files live in tools/welcome-export-samples/{en,ru}. To refresh them,
record tools/obsidian_cdp/scenarios/export-pages.mjs in each language and copy
the PDF/PPTX named after the scenario board from that isolated vault. No export runs in the plugin
when a welcome board is created; these offline examples are copied on request.
"""
import base64
import pathlib
import zipfile

root = pathlib.Path(__file__).resolve().parent.parent
lines = ["// Generated by tools/make_welcome_exports.py from real plugin exports.",
         "export const WELCOME_EXPORTS = {"]
for language in ("en", "ru"):
    lines.append(f"\t{language}: {{")
    for kind in ("pdf", "pptx"):
        path = root / "tools" / "welcome-export-samples" / language / f"Board-export.{kind}"
        data = path.read_bytes()
        if kind == "pdf":
            assert data.startswith(b"%PDF-") and data.rstrip().endswith(b"%%EOF")
        else:
            with zipfile.ZipFile(path) as package:
                assert package.testzip() is None
                assert "ppt/slides/slide2.xml" in package.namelist()
        lines.append(f'\t\t{kind}: "{base64.b64encode(data).decode()}",')
    lines.append("\t},")
lines.append("} as const;")
(root / "src" / "welcome-export-samples.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
