/**
 * The three sample attachments the welcome board's "Files and notes" frame
 * shows, so a fresh board has real files to point at, not a broken link.
 * Built once by tools/make_welcome_samples.py - see that script's header for
 * how each one is made and checked - and never derived at build or run
 * time; re-run it and replace this file when a sample's look should change.
 */

/** A 480x320 picture: a Miro-yellow sticky note and a blue card, joined by a line. */
export const WELCOME_SAMPLE_PNG_BASE64 =
	"iVBORw0KGgoAAAANSUhEUgAAAeAAAAFACAYAAABkyK97AAAFXklEQVR42u3dwW3CMBiAUYIqsQMTOCswCSMyCSvgCdiBU3qylEothZA4sf3eqaeKOiZf" +
	"/oSK3Q4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgBp1lgDYghDC" +
	"YBV4RYyxinYJMCC6iLEAA63G93i6WRRecr/2VURYgIHVwiu6zBnj0kK8d/gA8aVU431U2iMNAQbEFxEWYKClkyW0vK8EGMg2/YovOSJcyhQswID4IsIC" +
	"DABtEGAAEGCgJm4/s4ZSbkMLMAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDA" +
	"AIAAA4AAAwACDAACDAAIMAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAA" +
	"A4AAAwACDAACDAAIMAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAAA4AA" +
	"AwACDAACDAAIMAAIMAAIsCUAAAEGAAEGAAQYAAQYAJjuq+QXH0IYHELmEGPsrAIgwMLLSntKiAEBfjG+t8vBUeQj/fnxY3+JsAtkEOAnb2zhZS5pL6UQ" +
	"i7DwggD/8uYWXnKEWISFF5a29wYH+27q+jxbIxcwUMkEbPol5z4bPxfmvYsS4YVKAmwKYe39JyjCC01PwKZfTMHbC6/oQgMBBoQXBBhoLrpTwhtj7EII" +
	"w/3a746nm0Umi/u1L+JCUYBBeD3fBQEGthJe0YVl+TYkaDC8//3/7pzxTb8r3RaEJZVy+9kEDKbdLBOvZ8GIrwCD8GYM718nSRFmqfiWRIChwfCuMSGk" +
	"KViEWTK+JX12wTNgqCy8OZ/vTolwyRML4msCBl6edrd2YkqvJT0TTkzETIluieEVYBDe1UM8/htMxHxyQSfAwOrhLemENH6tvniFFqIrwCC8TqogwMDU" +
	"6AoXCDAgvIAAQ53hFV0QYEB4AQGG+qIrvCDAgPACAgx1hld0QYAB4QUEGOqLrvACAgzCCwgw1Ble0QUEGIQXEGCoL7rCCwgwCC8gwFBneEUXEGDISHgB" +
	"AQbhBQQYhBdAgEF4gQ3aWwIAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYABBgABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAQYAAQYAAQYABAgAFAgAEA" +
	"AQYAAQYABBgABBgAEGAAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYABBgABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAQYAAQYAAQYABAgAFAgAEAAQYA" +
	"AQYABBgABBgAEGAAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYABBgABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAQYAAQYAAQYABAgAFAgAEAAQYAAQYA" +
	"BBgABBgAEGAAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYABBgABBgAKCcAPfnh6OF/QYIcC4xxs5hwv4DBNhUgukXoI0Am0Kw74DaFHWCCSEM6efb5eDo" +
	"sdjkK76AAD+JsBAzd3jFFxDgNyIMcxFfQICFGOEFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
	"AAAAAAAAAAAAAAAAAAAAgE98A6qmf3rzc4L/AAAAAElFTkSuQmCC";

/** One Letter page reading "Miro Canvas" in Helvetica. */
export const WELCOME_SAMPLE_PDF_BASE64 =
	"JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRz" +
	"IFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzky" +
	"XSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA0IDAgUiA+PiA+PiAvQ29udGVudHMgNSAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL0Zv" +
	"bnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago1IDAgb2JqCjw8IC9MZW5ndGggNDIgPj4Kc3RyZWFtCkJUIC9G" +
	"MSAzMiBUZiA3MiA3MDAgVGQgKE1pcm8gQ2FudmFzKSBUaiBFVAplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA2CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAw" +
	"MDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwMzEx" +
	"IDAwMDAwIG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKNDAzCiUlRU9GCg==";

/** A one-paragraph Word document. */
export const WELCOME_SAMPLE_DOCX_BASE64 =
	"UEsDBBQAAAAIAJYLOV3JTxqw6wAAAK4BAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbH1QvU7DMBDeeQrLK4odGBBCSTrwMwJDeYCTfUks7LPlc0v79jht" +
	"6YAK4933q69b7YIXW8zsIvXyRrVSIJloHU29/Fi/NPdScAGy4CNhL/fIcjVcdet9QhZVTNzLuZT0oDWbGQOwigmpImPMAUo986QTmE+YUN+27Z02kQpS" +
	"acriIYfuCUfY+CKed/V9LJLRsxSPR+KS1UtIyTsDpeJ6S/ZXSnNKUFV54PDsEl9XgtQXExbk74CT7q0uk51F8Q65vEKoLP0Vs9U2mk2oSvW/zYWecRyd" +
	"wbN+cUs5GmSukwevzkgARz/99WHu4RtQSwMEFAAAAAgAlgs5XbmBRHGwAAAAKgEAAAsAAABfcmVscy8ucmVsc43POw7CMAwG4J1TRN5pWgaEUJMuCKkr" +
	"KgeIEjeNaB5KwqO3JwMDIAZG278/y233sDO5YUzGOwZNVQNBJ70yTjM4D8f1DkjKwikxe4cMFkzQ8VV7wlnkspMmExIpiEsMppzDntIkJ7QiVT6gK5PR" +
	"RytyKaOmQciL0Eg3db2l8d0A/mGSXjGIvWqADEvAf2w/jkbiwcurRZd/nPhKFFlEjZnB3UdF1atdFRYob+nHi/wJUEsDBBQAAAAIAJYLOV0axJlbzgAA" +
	"AP8AAAARAAAAd29yZC9kb2N1bWVudC54bWxFjrFOAzEMhneewspOczAgdLq7DkjdulExh0toT7rYURx67YbgEfoqZanaPkP6CjwJySHR5bMs29/varqx" +
	"PayN546wFneTQoDBlnSHy1osnme3jwI4KNSqJzS12BoW0+amGkpN7bs1GCAZkMuhFqsQXCkltytjFU/IGUyzN/JWhdT6pRzIa+epNcwpwPbyvigepFUd" +
	"iiYpX0lvc3UZPiM0884TPClcK4afjx28JAX8Z0uI+3iOh8tXPMbveLp8jguVzKeZfqQb+aeX19ebX1BLAQIUABQAAAAIAJYLOV3JTxqw6wAAAK4BAAAT" +
	"AAAAAAAAAAAAAACAAQAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAhQAFAAAAAgAlgs5XbmBRHGwAAAAKgEAAAsAAAAAAAAAAAAAAIABHAEAAF9yZWxz" +
	"Ly5yZWxzUEsBAhQAFAAAAAgAlgs5XRrEmVvOAAAA/wAAABEAAAAAAAAAAAAAAIAB9QEAAHdvcmQvZG9jdW1lbnQueG1sUEsFBgAAAAADAAMAuQAAAPIC" +
	"AAAAAA==";

/** Turns a base64 constant above into bytes `createBinary` can write, without Node's `Buffer` - the plugin also runs on mobile. */
export function decodeWelcomeSample(base64: string): Uint8Array {
	const binary = atob(base64);
	const bytes = new Uint8Array(binary.length);
	for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
	return bytes;
}
